server:
  port: 8006

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DarshanVNimap/HotelReviewSystem-Microservice-
          clone-on-start: true
  application:
    name: CONFIG-SERVER
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8004/eureka